version: "3"

services:
  app-first:
    build:
      context: .
      dockerfile: "./build/Dockerfile"
    container_name: app-first
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://app-first:9090/health" ]
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      PORT: "9090"
    networks:
      - app-network
    expose:
      - "9090"
    volumes:
      - ./logs:/logs

  app-second:
    build:
      context: .
      dockerfile: "./build/Dockerfile"
    container_name: app-second
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://app-second:1010/health" ]
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      PORT: "1010"
    networks:
      - app-network
    expose:
      - "1010"
    volumes:
      - ./logs:/logs

  app-third:
    build:
      context: .
      dockerfile: "./build/Dockerfile"
    container_name: app-third
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://app-third:2020/health" ]
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      PORT: "2020"
    networks:
      - app-network
    expose:
      - "2020"
    volumes:
      - ./logs:/logs

  app-fourth:
    build:
      context: .
      dockerfile: "./build/Dockerfile"
    container_name: app-fourth
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://app-fourth:3030/health" ]
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      PORT: "3030"
    networks:
      - app-network
    expose:
      - "3030"
    volumes:
      - ./logs:/logs

  app-backup:
    build:
      context: .
      dockerfile: "./build/Dockerfile"
    container_name: app-backup
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://app-backup:4040/health" ]
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      PORT: "4040"
    networks:
      - app-network
    expose:
      - "4040"
    volumes:
      - ./logs:/logs

  nginx:
    build:
      context: .
      dockerfile: "./build/config/nginx/Dockerfile"
    container_name: nginx
    networks:
      - app-network
    ports:
      - "90:90"
    depends_on:
      - app-first
      - app-second
      - app-third
      - app-fourth
      - app-backup
    volumes:
      - ./build/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./remove_cache.sh:/remove_cache.sh

networks:
  app-network:
    driver: bridge
